#!/bin/bash

JAVA="java"
#MADLA_PLANNER_JAR="Planner/madla-planner.jar"
MADLA_PLANNER_JAR="Planner/Planner.jar"

CREATOR=$1
DOMAIN=$2
PROBLEM=$3
AGENTS=$4
HEURISTIC=$5
RECURSION=$6
TIMEOUT=$7
        
timeout -s SIGSEGV $(($RECURSION+1))m $JAVA -Xmx8G -jar $MADLA_PLANNER_JAR $CREATOR $DOMAIN $PROBLEM $AGENTS $HEURISTIC $RECURSION $TIMEOUT
