appName: likely_model_generator
logLevel: INFO

input:
  traces:
    path: "C:\\Users/User/PycharmProjects/Thesis/LikelyModelGenerator/likelymodelgenerator/data"
    fileName: "p03-pfile3-3_Traces_20000"
    fileFormat: "txt"
  preprocessed:
    path: "C:\\Users/User/PycharmProjects/Thesis/LikelyModelGenerator/likelymodelgenerator/preprocessed"
    fileName: "preprocessed"
    fileFormat: "pkl" #csv


output:
  preprocess:
    path: "C:\\Users/User/PycharmProjects/Thesis/LikelyModelGenerator/likelymodelgenerator/preprocessed"
    fileName: "preprocessed"
    fileFormat: "pkl" #csv


workMode:
  preprocess: True
  load: True
  update: True