appName: likely_model_generator
logLevel: INFO
rootDir: '/home/daniel/Work/WorkSpace/Thesis/LikelyModelGenerator/likelymodelgenerator' #'C:\Users\User\PycharmProjects\Thesis\LikelyModelGenerator\likelymodelgenerator'

input:
  path: 'data'
  traces:
    fileName: 'probLOGISTICS-4-0-1_Traces_44.txt'
    tracesToUse : 0
  actions:
    fileName: 'ActionNames.txt'
  preconditions:
    fileName: 'Facts.txt'

working:
  path: 'working'
  iteration: 1
  deltaBase: 0.1 # TODO
  thresholdsBase: 0.8 # TODO
  data:
    fileName: 'Data.pkl'
  model:
    fileName: 'LastLikelyModel.pkl'


output:
  path: 'output'
  fileName: 'LikelyModel.txt'

workMode:
  preprocess: True
  load: True
  update: True